version: '3'
services:
  node1:
    image: node:${NODE_VERSION}
    container_name: node1
    environment:
      TZ: "$TZ"
    ports:
      - 8001:8001
    volumes:
      - /Users/long/Docker/docker-lnmp/app:/www/:rw
    working_dir: /www
    extra_hosts:
      - "boda.api:192.168.0.103"
    stdin_open: true
    tty: true
    networks:
      - public

  node2:
    image: node:${NODE_VERSION}
    container_name: node2
    environment:
      TZ: "$TZ"
    ports:
      - 8002:8001
    volumes:
      - /Users/long/Docker/docker-lnmp/app:/www/:rw
    working_dir: /www
    extra_hosts:
      - "boda.api:192.168.0.103"
    stdin_open: true
    tty: true
    networks:
      - public

  node3:
    image: node:${NODE_VERSION}
    container_name: node3
    environment:
      TZ: "$TZ"
    ports:
      - 8003:8001
    volumes:
      - /Users/long/Docker/docker-lnmp/app:/www/:rw
    working_dir: /www
    extra_hosts:
      - "boda.api:192.168.0.103"
    stdin_open: true
    tty: true
    networks:
      - public
      
  node4:
    image: node:${NODE_VERSION}
    container_name: node4
    environment:
      TZ: "$TZ"
    ports:
      - 8004:8001
    volumes:
      - /Users/long/Docker/docker-lnmp/app:/www/:rw
    working_dir: /www
    extra_hosts:
      - "boda.api:192.168.0.103"
    stdin_open: true
    tty: true
    networks:
      - public


networks:
  public:
    driver: bridge
    
