version: "3"
services:
  nginx:
    build:
      context: ./services/nginx
      args:
        NGINX_VERSION: nginx:${NGINX_VERSION}
        CONTAINER_PACKAGE_URL: ${CONTAINER_PACKAGE_URL}
        NGINX_INSTALL_APPS: ${NGINX_INSTALL_APPS}
    container_name: nginx
    ports:
      - "${NGINX_HTTP_HOST_PORT}:80"
      - "${NGINX_HTTPS_HOST_PORT}:443"
    volumes:
      - ${SOURCE_DIR}:/www/:rw
      - ${NGINX_SSL_CERTIFICATE_DIR}:/ssl:rw
      - ${NGINX_CONFD_DIR}:/etc/nginx/conf.d/:rw
      - ${NGINX_CONF_FILE}:/etc/nginx/nginx.conf:ro
      - ${NGINX_FASTCGI_PHP_CONF}:/etc/nginx/fastcgi-php.conf:ro
      - ${NGINX_FASTCGI_PARAMS}:/etc/nginx/fastcgi_params:ro
      - ${NGINX_LOG_DIR}:/var/log/nginx/:rw
    environment:
      TZ: "$TZ"
    restart: always
    networks:
      - default

  php:
    build:
      context: ./services/php
      args:
        PHP_VERSION: php:${PHP_VERSION}-fpm-alpine
        CONTAINER_PACKAGE_URL: ${CONTAINER_PACKAGE_URL}
        PHP_EXTENSIONS: ${PHP_EXTENSIONS}
        TZ: "$TZ"
    container_name: php
    depends_on:
      - "mysql"
      - "redis"
    expose:
      - 9501
    extra_hosts:
      - "boda.api:192.168.0.103"
      - "yaf.local:192.168.0.103"
      - "lam2.local:192.168.0.103"
    volumes:
      - ${SOURCE_DIR}:/www/:rw
      - ${PHP_PHP_CONF_FILE}:/usr/local/etc/php/php.ini:ro
      - ${PHP_FPM_CONF_FILE}:/usr/local/etc/php-fpm.d/www.conf:rw
      - ${PHP_LOG_DIR}:/var/log/php
      - ${DATA_DIR}/composer:/tmp/composer
    restart: always
    cap_add:
      - SYS_PTRACE
    networks:
      - default

  mysql:
    image: mysql:${MYSQL5_VERSION}
    container_name: mysql
    ports:
      - "3306:3306"
    volumes:
      - ${MYSQL5_CONF_FILE}:/etc/mysql/conf.d/mysql.cnf:ro
      - /Users/long/data/mysql:/var/lib/mysql/:rw
    restart: always
    networks:
      - default
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL5_ROOT_PASSWORD}"
      TZ: "$TZ"

  redis:
    image: redis:4.0
    container_name: redis
    restart: always
    environment:
      - REDIS_PASS_FILE=/run/secrets/redis-password
      - TZ=Asia/Shanghai
    command: [
      "bash", "-c",
      '
       docker-entrypoint.sh
       --requirepass "$$(cat $$REDIS_PASS_FILE)"
      '
    ]
    volumes:
      - ./data/redis/etc/redis.conf:/usr/local/etc/redis/redis.conf
      - ./data/redis/data:/data
      - ./data/redis/etc/redis-password:/run/secrets/redis-password
    networks:
      - default
    ports:
      - "6397:6379"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - "8080:80"
    networks:
      - default
    depends_on:
      - "mysql"
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - TZ=Asia/Shanghai

  phpredisadmin:
    image: erikdubbelboer/phpredisadmin
    container_name: phpredisadmin
    ports:
      - "8086:80"
    depends_on:
      - "redis"
    restart: always
    environment:
      - ADMIN_USER=admin
      - ADMIN_PASS=123456
      - REDIS_1_AUTH=123456
      - REDIS_1_HOST=redis
      - REDIS_1_PORT=6379
      - TZ=$TZ
    networks:
      - default


networks:
  default:
    driver: bridge

