version: '3'
services:
  node1:
    image: node:${NODE_VERSION}
    container_name: node1
    environment:
      TZ: "$TZ"
    ports:
      - 8001:8001
    volumes:
      - ${SOURCE_DIR}:/www/:rw
    working_dir: /www
    extra_hosts:
      - "boda.api:192.168.0.1"
    stdin_open: true
    tty: true
    networks:
      - public


networks:
  public:
    driver: bridge
    
